### PR TITLE
Fix links to chapters

### PR DESCRIPTION
**Pull request by mre**
Thought it might be helpful to support navigation to each chapter from the `README.md`.
The reason why it didn't work before was, that spaces need to be encoded to be recognized by the Markdown formatter. 
Alternatively, you could remove the spaces from the filenames if you like. 😊

### CODE REVIEW

**Comment by dumindu** [comment]
Hi,
Thanks for the PR. This project was moved to www.learning-rust.github.io with more content and a better UX. 
However I might update the gitbook later. Feedbacks are very welcome :)

**Comment by dumindu** [comment]
https://learning-rust.github.io/

**Comment by mre** [comment]
Wow, nice progress! As far as I can tell, this PR is therefore unneeded. Closing. 😄

**Comment by dumindu** [comment]
No, It's okay to reopen it. I need to maintain the gitbook as well. The issue was the time.

**Pull request merged**
